### ISSUE TITLE
[ENHANCEMENT] Invalid entries in Sonarr's queue leaves varken unable to process the rest of the queue

### ISSUE THREAD

**Issue by samwiseg0** [Boerderij/Varken#117]
```
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.7/threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "/app/Varken.py", line 34, in thread
a = job()
File "/app/varken/sonarr.py", line 146, in get_queue
sxe = f"S{show.episode['seasonNumber']:0>2}E{show.episode['episodeNumber']:0>2}"
TypeError: 'NoneType' object is not subscriptable
```

We log the error and skip over the invalid entry.

**Comment by DirtyCajunRice** [comment]
nice
