### ISSUE TITLE
[Bug] Varken Crashes when ini is read only

### ISSUE THREAD

**Issue by rmzg** [Boerderij/Varken#146]
I run Varken inside a kubernetes using its ConfigMap object to provide the actual config file, as a result of this the actual config file inside the docker image is read only (since it's being provided from another location). However, when varken detects a missing config stanza it attempts to rewrite the config file and this causes a crash since it can't open the file for writing.

Suggestion: if a config option is missing, attempt to rewrite the file but gracefully fail if this isn't possible and continue running with default values where possible. Since my case involves missing top level configs (ombi) it should be pretty ignorable.

```
Traceback (most recent call last):
  File "/app/varken/iniparser.py", line 25, in __init__
    self.parse_opts(read_file=True)
  File "/app/varken/iniparser.py", line 177, in parse_opts
    url = self.url_check(env.get(f'VRKN_{envsection}_URL', self.config.get(section, 'url')),
  File "/usr/local/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'ombi-0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/Varken.py", line 92, in <module>
    CONFIG = INIParser(DATA_FOLDER)
  File "/app/varken/iniparser.py", line 28, in __init__
    self.rectify_ini()
  File "/app/varken/iniparser.py", line 133, in rectify_ini
    self.write_file('varken.ini')
  File "/app/varken/iniparser.py", line 80, in write_file
    with open(file_path, 'w') as config_ini:
OSError: [Errno 30] Read-only file system: '/config/varken.ini'
```

**Comment by DirtyCajunRice** [comment]
Why not just use environment variables since you use k8s?

**Comment by samwiseg0** [comment]
I agree we should not crash but I disagree that Varken should continue to run. We should exit if we cannot write the config file if it is invalid.

**Comment by rmzg** [comment]
A) I don't use environment variables because I didn't know they were an option and I don't understand how they apply in this situation

B) There may be some cases where the config file is invalid to the point of not being able to run, in this specific case (and the last couple of times this has happened), the problem is merely missing config blocks for services that aren't even enabled.

In other words, the config is valid, you add support for a new service (ombi) and suddenly the config becomes invalid and varken starts crashing trying to rewrite the config file. This seems pretty unnecessary, no?

**Comment by DirtyCajunRice** [comment]
Env vars are brand new so no harm no foul there! As for a new service, the block does not need to be there if the global is defined as false, but there _does_ need to be a global server ids section for false. Maybe that is where the disconnect is?

**Comment by rmzg** [comment]
Well, in my current config I have this line:
```
sickchill_server_ids = 0
```

and varken crashes with the error:
```
2019-07-07 17:54:38 : DEBUG : iniparser : Section sickchill-1 missing. Adding...
2019-07-07 17:54:38 : DEBUG : iniparser : url is missing in sickchill-1. Adding defaults...
2019-07-07 17:54:38 : DEBUG : iniparser : apikey is missing in sickchill-1. Adding defaults...
2019-07-07 17:54:38 : DEBUG : iniparser : ssl is missing in sickchill-1. Adding defaults...
2019-07-07 17:54:38 : DEBUG : iniparser : verify_ssl is missing in sickchill-1. Adding defaults...
2019-07-07 17:54:38 : DEBUG : iniparser : get_missing is missing in sickchill-1. Adding defaults...
2019-07-07 17:54:38 : DEBUG : iniparser : get_missing_run_seconds is missing in sickchill-1. Adding defaults...
2019-07-07 17:54:38 : DEBUG : iniparser : Writing to varken.ini
Traceback (most recent call last):
  File "/app/varken/iniparser.py", line 25, in __init__
    self.parse_opts(read_file=True)
  File "/app/varken/iniparser.py", line 177, in parse_opts
    url = self.url_check(env.get(f'VRKN_{envsection}_URL', self.config.get(section, 'url')),
  File "/usr/local/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'ombi-0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/Varken.py", line 92, in <module>
    CONFIG = INIParser(DATA_FOLDER)
  File "/app/varken/iniparser.py", line 28, in __init__
    self.rectify_ini()
  File "/app/varken/iniparser.py", line 133, in rectify_ini
    self.write_file('varken.ini')
  File "/app/varken/iniparser.py", line 80, in write_file
    with open(file_path, 'w') as config_ini:
OSError: [Errno 30] Read-only file system: '/config/varken.ini'
```

I feel like the global server id = 0 used to be sufficient, since it worked when I added this a while ago, but it no longer works that way.

**Comment by DirtyCajunRice** [comment]
0 no longer works and an explicit false is required. This was changed in the last release
