### ISSUE TITLE
Logs full of "Resetting dropped connection"

### ISSUE THREAD

**Issue by tehniemer** [Boerderij/Varken#151]
My logs are full of the following and the download queue and missing items fields are not populating in Grafana.

```

2019-08-31 11:30:48 : INFO : __init__ : Running job Every 30 seconds do thread(<bound method TautulliAPI.get_activity of <tautulli-1>>) (last run: 2019-08-31 11:30:18, next run: 2019-08-31 11:30:48)


2019-08-31 11:30:48 : DEBUG : connectionpool : Resetting dropped connection: ********tulli


2019-08-31 11:30:48 : DEBUG : connectionpool : http://********tulli:8181 "GET /api/v2?apikey=********90e44&cmd=get_activity HTTP/1.1" 200 149


2019-08-31 11:30:48 : DEBUG : dbmanager : Writing Data to InfluxDB [{'measurement': 'Tautulli', 'tags': {'type': 'current_stream_stats', 'server': 1}, 'time': '2019-08-31T11:30:48.959218-05:00', 'fields': {'stream_count': 0, 'total_bandwidth': 0, 'wan_bandwidth': 0, 'lan_bandwidth': 0, 'transcode_streams': 0, 'direct_play_streams': 0, 'direct_streams': 0}}]


2019-08-31 11:30:48 : DEBUG : connectionpool : http://********luxdb:8086 "POST /write?db=varken HTTP/1.1" 204 0


2019-08-31 11:31:03 : INFO : __init__ : Running job Every 300 seconds do thread(<bound method SonarrAPI.get_queue of <sonarr-1>>) (last run: 2019-08-31 11:26:03, next run: 2019-08-31 11:31:03)


2019-08-31 11:31:03 : DEBUG : connectionpool : Resetting dropped connection: ********onarr


2019-08-31 11:31:03 : INFO : __init__ : Running job Every 300 seconds do thread(<bound method SonarrAPI.get_calendar of <sonarr-1>>, query='Missing') (last run: 2019-08-31 11:26:03, next run: 2019-08-31 11:31:03)


2019-08-31 11:31:03 : DEBUG : connectionpool : Resetting dropped connection: ********onarr


2019-08-31 11:31:03 : DEBUG : connectionpool : http://********onarr:8989 "GET /api/queue?pageSize=1000 HTTP/1.1" 200 None


2019-08-31 11:31:03 : DEBUG : connectionpool : http://********onarr:8989 "GET /api/calendar/?pageSize=1000&start=2019-08-24&end=2019-08-31 HTTP/1.1" 200 None


2019-08-31 11:31:03 : DEBUG : dbmanager : Writing Data to InfluxDB []


2019-08-31 11:31:03 : DEBUG : connectionpool : http://********luxdb:8086 "POST /write?db=varken HTTP/1.1" 204 0


2019-08-31 11:31:04 : INFO : __init__ : Running job Every 300 seconds do thread(<bound method SonarrAPI.get_calendar of <sonarr-1>>, query='Future') (last run: 2019-08-31 11:26:04, next run: 2019-08-31 11:31:04)


2019-08-31 11:31:04 : INFO : __init__ : Running job Every 300 seconds do thread(<bound method RadarrAPI.get_missing of <radarr-1>>) (last run: 2019-08-31 11:26:04, next run: 2019-08-31 11:31:04)


2019-08-31 11:31:04 : DEBUG : connectionpool : Resetting dropped connection: ********adarr


2019-08-31 11:31:04 : INFO : __init__ : Running job Every 300 seconds do thread(<bound method RadarrAPI.get_queue of <radarr-1>>) (last run: 2019-08-31 11:26:04, next run: 2019-08-31 11:31:04)


2019-08-31 11:31:04 : INFO : __init__ : Running job Every 300 seconds do thread(<bound method OmbiAPI.get_request_counts of <ombi-1>>) (last run: 2019-08-31 11:26:04, next run: 2019-08-31 11:31:04)


2019-08-31 11:31:04 : DEBUG : connectionpool : Resetting dropped connection: ********adarr


2019-08-31 11:31:04 : DEBUG : connectionpool : Resetting dropped connection: ****************ombi


2019-08-31 11:31:04 : INFO : __init__ : Running job Every 300 seconds do thread(<bound method OmbiAPI.get_all_requests of <ombi-1>>) (last run: 2019-08-31 11:26:04, next run: 2019-08-31 11:31:04)


2019-08-31 11:31:04 : DEBUG : connectionpool : http://********onarr:8989 "GET /api/calendar/?pageSize=1000&start=2019-08-31&end=2019-09-01 HTTP/1.1" 200 None


2019-08-31 11:31:05 : DEBUG : connectionpool : Resetting dropped connection: ****************ombi


2019-08-31 11:31:05 : DEBUG : connectionpool : http://********adarr:7878 "GET /api/movie HTTP/1.1" 500 None


2019-08-31 11:31:05 : INFO : __init__ : Running job Every 300 seconds do thread(<bound method OmbiAPI.get_issue_counts of <ombi-1>>) (last run: 2019-08-31 11:26:04, next run: 2019-08-31 11:31:04)


2019-08-31 11:31:05 : DEBUG : connectionpool : http://********adarr:7878 "GET /api/queue HTTP/1.1" 200 None


2019-08-31 11:31:05 : DEBUG : connectionpool : Resetting dropped connection: ****************ombi


2019-08-31 11:31:05 : DEBUG : connectionpool : http://****************ombi:3579 "GET /api/v1/Request/count HTTP/1.1" 200 None


2019-08-31 11:31:05 : DEBUG : dbmanager : Writing Data to InfluxDB [{'measurement': 'Ombi', 'tags': {'type': 'Request_Counts'}, 'time': '2019-08-31T11:31:04.995303-05:00', 'fields': {'pending': 0, 'approved': 0, 'available': 0}}]


2019-08-31 11:31:05 : DEBUG : connectionpool : http://********luxdb:8086 "POST /write?db=varken HTTP/1.1" 204 0


2019-08-31 11:31:05 : DEBUG : connectionpool : http://****************ombi:3579 "GET /api/v1/Issues/count HTTP/1.1" 200 None


2019-08-31 11:31:05 : DEBUG : dbmanager : Writing Data to InfluxDB [{'measurement': 'Ombi', 'tags': {'type': 'Issues_Counts'}, 'time': '2019-08-31T11:31:05.009269-05:00', 'fields': {'pending': 0, 'in_progress': 0, 'resolved': 0}}]


2019-08-31 11:31:05 : DEBUG : connectionpool : http://********luxdb:8086 "POST /write?db=varken HTTP/1.1" 204 0


2019-08-31 11:31:05 : DEBUG : connectionpool : http://****************ombi:3579 "GET /api/v1/Request/tv HTTP/1.1" 200 None


2019-08-31 11:31:05 : DEBUG : connectionpool : http://****************ombi:3579 "GET /api/v1/Request/movie HTTP/1.1" 200 None


2019-08-31 11:31:05 : ERROR : ombi : No json replies. Discarding job


Exception in thread Thread-3624:


Traceback (most recent call last):


  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner


    self.run()


  File "/usr/local/lib/python3.7/threading.py", line 865, in run


    self._target(*self._args, **self._kwargs)


  File "/app/varken/radarr.py", line 85, in get_queue


    movie['movie'] = RadarrMovie(**movie['movie'])


KeyError: 'movie'
```

**Comment by samwiseg0** [comment]
Issues is not the place for support. Please use discord as outlined in [Asking for support](https://wiki.cajun.pro/books/varken/page/before-asking-for-support-make-sure-you-try-these-things-first)
