### ISSUE TITLE
[BUG] Help with Varken Docker Setup

### ISSUE THREAD

**Issue by ItsRainingHP** [Boerderij/Varken#208]
**Describe the bug**
I have been trying to setup Varken unsuccessfully for quite a while now. 

**To Reproduce**
1. Install and run InfluxDB 2.0 Docker
2. Install and run Varken Docker
3. Set influxdb url variable to internal IP of Synology, localhost, and Influxdb.
4. Set PUID/PGID to Varken, root, and admin IDs.

**Expected behavior**
I am just trying to get the Varken docker app to configure with Grafana.

**Screenshots**
I will post screens upon request.

**Environment (please complete the following information):**
 - OS: Synology DSM
 - Version 6.2.4

**Additional context**
Here is the build:

```
{
    "AppArmorProfile": "unconfined",
    "Args": [
        "-c",
        "cp /app/data/varken.example.ini /config/varken.example.ini && python3 /app/Varken.py"
    ],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [
            "/bin/sh",
            "-c",
            "cp /app/data/varken.example.ini /config/varken.example.ini && python3 /app/Varken.py"
        ],
        "DDSM": false,
        "Domainname": "",
        "Entrypoint": null,
        "Env": [
            "PGID=100",
            "PUID=1028",
            "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "LANG=C.UTF-8",
            "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568",
            "PYTHON_VERSION=3.9.1",
            "PYTHON_PIP_VERSION=20.3.3",
            "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/5f38681f7f5872e4032860b54e9cc11cf0374932/get-pip.py",
            "PYTHON_GET_PIP_SHA256=6a0b13826862f33c13b614a921d36253bfa1ae779c5fbf569876f3585057e9d2",
            "DEBUG=True",
            "DATA_FOLDER=/config",
            "VERSION=0.0.0",
            "BRANCH=edge",
            "BUILD_DATE=1/1/1970",
            "TZ=America/Los_Angeles"
        ],
        "Hostname": "varken",
        "Image": "boerderij/varken:latest",
        "Labels": {
            "maintainer": "dirtycajunrice,samwiseg0",
            "org.opencontainers.image.created": "1/1/1970",
            "org.opencontainers.image.description": "Varken is a standalone application to aggregate data from the Plex ecosystem into InfluxDB using Grafana for a frontend",
            "org.opencontainers.image.licenses": "MIT",
            "org.opencontainers.image.revision": "",
            "org.opencontainers.image.source": "https://github.com/Boerderij/Varken",
            "org.opencontainers.image.title": "varken",
            "org.opencontainers.image.url": "https://github.com/Boerderij/Varken",
            "org.opencontainers.image.vendor": "boerderij",
            "org.opencontainers.image.version": "0.0.0"
        },
        "OnBuild": null,
        "OpenStdin": true,
        "StdinOnce": false,
        "Tty": true,
        "User": "",
        "Volumes": null,
        "WorkingDir": "/app"
    },
    "Created": "2021-07-18T07:18:20.569134103Z",
    "Driver": "btrfs",
    "ExecIDs": null,
    "GraphDriver": {
        "Data": null,
        "Name": "btrfs"
    },
    "HostConfig": {
        "AutoRemove": false,
        "Binds": [
            "/volume1/Config/varken:/config:rw"
        ],
        "BlkioDeviceReadBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceWriteIOps": null,
        "BlkioWeight": 0,
        "BlkioWeightDevice": null,
        "CapAdd": null,
        "CapDrop": null,
        "Cgroup": "",
        "CgroupParent": "",
        "CgroupnsMode": "host",
        "ConsoleSize": [
            0,
            0
        ],
        "ContainerIDFile": "",
        "CpuCount": 0,
        "CpuPercent": 0,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpuShares": 50,
        "CpusetCpus": "",
        "CpusetMems": "",
        "DeviceCgroupRules": null,
        "DeviceRequests": null,
        "Devices": null,
        "Dns": null,
        "DnsOptions": null,
        "DnsSearch": null,
        "Env": [
            "PGID=100",
            "PUID=1028",
            "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "LANG=C.UTF-8",
            "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568",
            "PYTHON_VERSION=3.9.1",
            "PYTHON_PIP_VERSION=20.3.3",
            "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/5f38681f7f5872e4032860b54e9cc11cf0374932/get-pip.py",
            "PYTHON_GET_PIP_SHA256=6a0b13826862f33c13b614a921d36253bfa1ae779c5fbf569876f3585057e9d2",
            "DEBUG=True",
            "DATA_FOLDER=/config",
            "VERSION=0.0.0",
            "BRANCH=edge",
            "BUILD_DATE=1/1/1970",
            "TZ=America/Los_Angeles"
        ],
        "ExtraHosts": null,
        "GroupAdd": null,
        "IOMaximumBandwidth": 0,
        "IOMaximumIOps": 0,
        "IpcMode": "private",
        "Isolation": "",
        "KernelMemory": 0,
        "KernelMemoryTCP": 0,
        "Links": null,
        "LogConfig": {
            "Config": {},
            "Type": "db"
        },
        "MaskedPaths": null,
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "NanoCpus": 0,
        "NetworkMode": "bridge",
        "OomKillDisable": false,
        "OomScoreAdj": 0,
        "PidMode": "",
        "PidsLimit": null,
        "PortBindings": {},
        "Privileged": true,
        "PublishAllPorts": false,
        "ReadonlyPaths": null,
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "always"
        },
        "Runtime": "runc",
        "SecurityOpt": [
            "label=disable"
        ],
        "ShmSize": 67108864,
        "UTSMode": "",
        "Ulimits": null,
        "UsernsMode": "",
        "VolumeDriver": "",
        "VolumesFrom": null
    },
    "HostnamePath": "/volume1/@docker/containers/167cfdba68b46bf25dcc1aba59ef21abf996ae44c6b6867d0c257658a77a27c1/hostname",
    "HostsPath": "/volume1/@docker/containers/167cfdba68b46bf25dcc1aba59ef21abf996ae44c6b6867d0c257658a77a27c1/hosts",
    "Id": "167cfdba68b46bf25dcc1aba59ef21abf996ae44c6b6867d0c257658a77a27c1",
    "Image": "sha256:6fd92843e82ddb4d1d8cb6286956436cc07dcc75d0f3e2519d380ecd44b8c69b",
    "LogPath": "/volume1/@docker/containers/167cfdba68b46bf25dcc1aba59ef21abf996ae44c6b6867d0c257658a77a27c1/log.db",
    "MountLabel": "",
    "Mounts": [
        {
            "Destination": "/config",
            "Mode": "rw",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/volume1/Config/varken",
            "Type": "bind"
        }
    ],
    "Name": "/varken",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "Networks": {
            "bridge": {
                "Aliases": null,
                "DriverOpts": null,
                "EndpointID": "",
                "Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAMConfig": null,
                "IPAddress": "",
                "IPPrefixLen": 0,
                "IPv6Gateway": "",
                "Links": null,
                "MacAddress": "",
                "NetworkID": "105c2ba796c2875eb16f70f221b452456f28e44e50771b2c2ba135219326a33e"
            }
        },
        "Ports": {},
        "SandboxID": "b02da55c293c6fa3396c14c98025366b5e1f7795c0b203c1f79bd91c108fde91",
        "SandboxKey": "/var/run/docker/netns/b02da55c293c",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "Path": "/bin/sh",
    "Platform": "linux",
    "ProcessLabel": "",
    "ResolvConfPath": "/volume1/@docker/containers/167cfdba68b46bf25dcc1aba59ef21abf996ae44c6b6867d0c257658a77a27c1/resolv.conf",
    "RestartCount": 1,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 1,
        "FinishedAt": "2021-07-18T16:44:57.875575355Z",
        "FinishedTs": 1626626697,
        "OOMKilled": false,
        "Paused": false,
        "Pid": 0,
        "Restarting": false,
        "Running": false,
        "StartedAt": "2021-07-18T16:44:57.371753791Z",
        "StartedTs": 1626626697,
        "Status": "exited"
    }
}
```

Here is the Varken.ini

```
[global]
sonarr_server_ids = 1,2
radarr_server_ids = 1,2
lidarr_server_ids = false
tautulli_server_ids = 1
ombi_server_ids = 1
sickchill_server_ids = false
unifi_server_ids = false
maxmind_license_key = HIDDEN

[influxdb]
url = 192.168.0.216
port = 8086
ssl = false
verify_ssl = false
username = varken
password = XXXXXXXXXX

[tautulli-1]
url = 127.0.0.1:8181
fallback_ip = this_is_set_to_my_external_ip
apikey = HIDDEN
ssl = false
verify_ssl = false
get_activity = true
get_activity_run_seconds = 30
get_stats = true
get_stats_run_seconds = 3600

[sonarr-1]
url = set_to_reverse_proxy_address
apikey = HIDDEN
ssl = false
verify_ssl = false
missing_days = 7
missing_days_run_seconds = 300
future_days = 1
future_days_run_seconds = 300
queue = true
queue_run_seconds = 300

[sonarr-2]
url = 192.168.0.216:32784
apikey = HIDDEN
ssl = false
verify_ssl = false
missing_days = 7
missing_days_run_seconds = 300
future_days = 1
future_days_run_seconds = 300
queue = true
queue_run_seconds = 300

[radarr-1]
url = set_to_reverse_proxy_address
apikey = HIDDEN
ssl = false
verify_ssl = false
queue = true
queue_run_seconds = 300
get_missing = true
get_missing_run_seconds = 300

[radarr-2]
url = 192.168.0.216:32783
apikey = HIDDEN
ssl = false
verify_ssl = false
queue = true
queue_run_seconds = 300
get_missing = true
get_missing_run_seconds = 300

[lidarr-1]
url = lidarr1.domain.tld:8686
apikey = xxxxxxxxxxxxxxxx
ssl = false
verify_ssl = false
missing_days = 30
missing_days_run_seconds = 300
future_days = 30
future_days_run_seconds = 300
queue = true
queue_run_seconds = 300

[ombi-1]
url = set_to_reverse_proxy_address
apikey = HIDDEN
ssl = false
verify_ssl = false
get_request_type_counts = true
request_type_run_seconds = 300
get_request_total_counts = true
request_total_run_seconds = 300
get_issue_status_counts = true
issue_status_run_seconds = 300

[sickchill-1]
url = sickchill.domain.tld:8081
apikey = xxxxxxxxxxxxxxxx
ssl = false
verify_ssl = false
get_missing = true
get_missing_run_seconds = 300

[unifi-1]
url = unifi.domain.tld:8443
username = ubnt
password = ubnt
site = default
usg_name = MyRouter
ssl = false
verify_ssl = false
get_usg_stats_run_seconds = 300
```

Here is my output log:

```
2021-07-18 08:22:01 : INFO : Varken : Starting Varken...
2021-07-18 08:22:01 : INFO : Varken : Data folder is "/config"
2021-07-18 08:22:01 : INFO : Varken : Linux 4.4.59+ (#25556 SMP PREEMPT Thu Mar 18 13:00:35 CST 2021 - Alpine Linux 3.12.3)
2021-07-18 08:22:01 : INFO : Varken : Python 3.9.1 (default, Dec 17 2020, 01:59:58) 
[GCC 9.3.0]
2021-07-18 08:22:01 : INFO : Varken : Varken v0.0.0-edge 1/1/1970
2021-07-18 08:22:01 : DEBUG : iniparser : Reading from varken.ini
2021-07-18 08:22:01 : DEBUG : iniparser : ********0.216 is a valid URL in module [influxdb].
2021-07-18 08:22:01 : INFO : helpers : SONARR_SERVER_IDS : [1, 2]
2021-07-18 08:22:01 : DEBUG : iniparser : ********x.com is a valid URL in module [sonarr-1].
2021-07-18 08:22:01 : DEBUG : iniparser : ********32784 is a valid URL in module [sonarr-2].
2021-07-18 08:22:01 : INFO : helpers : RADARR_SERVER_IDS : [1, 2]
2021-07-18 08:22:01 : DEBUG : iniparser : ********x.com is a valid URL in module [radarr-1].
2021-07-18 08:22:01 : DEBUG : iniparser : ********32783 is a valid URL in module [radarr-2].
2021-07-18 08:22:01 : INFO : iniparser : LIDARR_SERVER_IDS disabled.
2021-07-18 08:22:01 : INFO : helpers : OMBI_SERVER_IDS : [1]
2021-07-18 08:22:01 : DEBUG : iniparser : ********x.com is a valid URL in module [ombi-1].
2021-07-18 08:22:01 : INFO : helpers : TAUTULLI_SERVER_IDS : [1]
2021-07-18 08:22:01 : DEBUG : iniparser : ********:8181 is a valid URL in module [tautulli-1].
2021-07-18 08:22:01 : INFO : iniparser : SICKCHILL_SERVER_IDS disabled.
2021-07-18 08:22:01 : INFO : iniparser : UNIFI_SERVER_IDS disabled.
2021-07-18 08:22:01 : DEBUG : connectionpool : Starting new HTTP connection (1): ********0.216:8086
2021-07-18 08:22:01 : DEBUG : connectionpool : http://********0.216:8086 "GET /ping HTTP/1.1" 204 0
2021-07-18 08:22:01 : INFO : dbmanager : Influxdb version: 
2021-07-18 08:22:01 : DEBUG : connectionpool : http://********0.216:8086 "GET /query?q=SHOW+DATABASES&db=********arken HTTP/1.1" 401 48
Traceback (most recent call last):
  File "/app/Varken.py", line 93, in <module>
    DBMANAGER = DBManager(CONFIG.influx_server)
  File "/app/varken/dbmanager.py", line 25, in __init__
    databases = [db['name'] for db in self.influx.get_list_database()]
  File "/usr/local/lib/python3.9/site-packages/influxdb/client.py", line 570, in get_list_database
    return list(self.query("SHOW DATABASES").get_points())
  File "/usr/local/lib/python3.9/site-packages/influxdb/client.py", line 411, in query
    response = self.request(
  File "/usr/local/lib/python3.9/site-packages/influxdb/client.py", line 286, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.exceptions.InfluxDBClientError: 401: {"code":"unauthorized","message":"Unauthorized"}
2021-07-18 08:22:03 : INFO : Varken : Starting Varken...
2021-07-18 08:22:03 : INFO : Varken : Data folder is "/config"
2021-07-18 08:22:03 : INFO : Varken : Linux 4.4.59+ (#25556 SMP PREEMPT Thu Mar 18 13:00:35 CST 2021 - Alpine Linux 3.12.3)
2021-07-18 08:22:03 : INFO : Varken : Python 3.9.1 (default, Dec 17 2020, 01:59:58) 
[GCC 9.3.0]
2021-07-18 08:22:03 : INFO : Varken : Varken v0.0.0-edge 1/1/1970
2021-07-18 08:22:03 : DEBUG : iniparser : Reading from varken.ini
2021-07-18 08:22:03 : DEBUG : iniparser : ********0.216 is a valid URL in module [influxdb].
2021-07-18 08:22:03 : INFO : helpers : SONARR_SERVER_IDS : [1, 2]
2021-07-18 08:22:03 : DEBUG : iniparser : ********x.com is a valid URL in module [sonarr-1].
2021-07-18 08:22:03 : DEBUG : iniparser : ********0.216:32784 is a valid URL in module [sonarr-2].
2021-07-18 08:22:03 : INFO : helpers : RADARR_SERVER_IDS : [1, 2]
2021-07-18 08:22:03 : DEBUG : iniparser : ********x.com is a valid URL in module [radarr-1].
2021-07-18 08:22:03 : DEBUG : iniparser : ********32783 is a valid URL in module [radarr-2].
2021-07-18 08:22:03 : INFO : iniparser : LIDARR_SERVER_IDS disabled.
2021-07-18 08:22:03 : INFO : helpers : OMBI_SERVER_IDS : [1]
2021-07-18 08:22:03 : DEBUG : iniparser : ********x.com is a valid URL in module [ombi-1].
2021-07-18 08:22:03 : INFO : helpers : TAUTULLI_SERVER_IDS : [1]
2021-07-18 08:22:03 : DEBUG : iniparser : ********:8181 is a valid URL in module [tautulli-1].
2021-07-18 08:22:03 : INFO : iniparser : SICKCHILL_SERVER_IDS disabled.
2021-07-18 08:22:03 : INFO : iniparser : UNIFI_SERVER_IDS disabled.
2021-07-18 08:22:03 : DEBUG : connectionpool : Starting new HTTP connection (1): ********0.216:8086
2021-07-18 08:22:03 : DEBUG : connectionpool : http://********0.216:8086 "GET /ping HTTP/1.1" 204 0
2021-07-18 08:22:03 : INFO : dbmanager : Influxdb version: 
2021-07-18 08:22:03 : DEBUG : connectionpool : http://********0.216:8086 "GET /query?q=SHOW+DATABASES&db=********arken HTTP/1.1" 401 48
Traceback (most recent call last):
  File "/app/Varken.py", line 93, in <module>
    DBMANAGER = DBManager(CONFIG.influx_server)
  File "/app/varken/dbmanager.py", line 25, in __init__
    databases = [db['name'] for db in self.influx.get_list_database()]
  File "/usr/local/lib/python3.9/site-packages/influxdb/client.py", line 570, in get_list_database
    return list(self.query("SHOW DATABASES").get_points())
  File "/usr/local/lib/python3.9/site-packages/influxdb/client.py", line 411, in query
    response = self.request(
  File "/usr/local/lib/python3.9/site-packages/influxdb/client.py", line 286, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.exceptions.InfluxDBClientError: 401: {"code":"unauthorized","message":"Unauthorized"}
```

**Comment by samwiseg0** [comment]
This is not a bug. Varken does not currently support 2.0. You must use 1.8.x. Please see the note at top of the installation page. https://wiki.cajun.pro/books/varken/page/influxdb-d1f

In the future please use discord for support issues.

**Comment by ItsRainingHP** [comment]
I knew it would be something so simple XD. Thank you! I will use discord although that is likely why this is so hard to google issues on.
