### ISSUE TITLE
[BUG] Documentation Tautulli url base

### ISSUE THREAD

**Issue by jackaroo9** [Boerderij/Varken#87]
**Describe the bug**
Tautulli requires url base to if it is set. 

**To Reproduce**
1. Add url base to Tautulli application
2. configure Varken without it

**Expected behavior**
Update Wiki documents and example ini file to notify of this requirement 

```
[tautulli-1]
url = 192.168.2.158:8282/tautulli
```

**Screenshots**
`2019-01-07 11:02:37 : INFO : helpers : This url doesnt even resolve: http://********2.158:8282/api/v2?apikey=********62d7f&cmd=get_activity`

**Environment (please complete the following information):**
 - OS: Linux 4.18.20-unRAID x86_64
 - Version 6.6.6

**Additional context**
Sonarr & Radarr do not have this requirement

**Comment by DirtyCajunRice** [comment]
this is not an issue with varken. This is the expected functionality of tautulli. If you set a base url IN tautulli and then go to http://tautulli_ip:tautulli_port it will redirect you to tautulli_ip:tautulli_port/tautulli_url_base.

**Comment by jackaroo9** [comment]
I agree it is working correctly and varken is not the problem. My concern is the project documents don't mention this and I thought it would be helpful to others to have this info local to the project instead of discovering from other sources. Given that Radarr and Sonarr do not behave the same way it might be useful to point that difference in the wiki.

**Comment by johntdyer** [comment]
yea, thius doesnt work w/ or w/o the base url 

```
2019-03-18 23:18:46 : INFO : __init__ : Running *all* 4 jobs with 0s delay inbetween
2019-03-18 23:18:46 : INFO : __init__ : Running job Every 12 to 24 hours do put(<bound method GeoIPHandler.update of <varken.helpers.GeoIPHandler object at 0x7f9259e4bc18>>) (last run: [never], next run: 2019-03-19 15:18:45)
2019-03-18 23:18:46 : INFO : __init__ : Running job Every 30 seconds do put(<bound method TautulliAPI.get_activity of <tautulli-1>>) (last run: [never], next run: 2019-03-18 23:19:15)
2019-03-18 23:18:46 : INFO : __init__ : Running job Every 3600 seconds do put(<bound method TautulliAPI.get_stats of <tautulli-1>>) (last run: [never], next run: 2019-03-19 00:18:45)
2019-03-18 23:18:46 : INFO : __init__ : Running job Every 300 seconds do put(<bound method UniFiAPI.get_usg_stats of <unifi-1>>) (last run: [never], next run: 2019-03-18 23:23:46)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/Varken/Varken.py", line 34, in thread
    a = job()
  File "/opt/Varken/varken/tautulli.py", line 38, in get_activity
    for session in get['sessions']:
KeyError: 'sessions'

```

my config is 

```
[tautulli-1]
url = 127.0.0.1:8181
fallback_ip = 1.1.1.1
apikey = xxxxx
ssl = false
verify_ssl = false
get_activity = true
get_activity_run_seconds = 30
get_stats = true
get_stats_run_seconds = 3600
```

I have also tried 

```
[tautulli-1]
url = 127.0.0.1:8181/tautulli
fallback_ip = 1.1.1.1
apikey = xxxxxxx
ssl = false
verify_ssl = false
get_activity = true
get_activity_run_seconds = 30
get_stats = true
get_stats_run_seconds = 3600
```

**Comment by samwiseg0** [comment]
@johntdyer I have already stated this. Do not use issues for support. We only do support in discord.
